-- Create booking_slot table
CREATE TABLE IF NOT EXISTS booking_slot (
    id_slot BIGINT AUTO_INCREMENT PRIMARY KEY,
    tanggal DATE NOT NULL,
    jam TIME NOT NULL,
    jumlah_terisi INT NOT NULL DEFAULT 0,
    UNIQUE KEY unique_slot (tanggal, jam)
);

-- Insert initial time slots for the next 30 days
-- Time slots from 8:00 AM to 6:00 PM (every hour)
INSERT IGNORE INTO booking_slot (tanggal, jam, jumlah_terisi) 
SELECT 
    DATE_ADD(CURDATE(), INTERVAL seq DAY) as tanggal,
    TIME(CONCAT(hour_val, ':00:00')) as jam,
    0 as jumlah_terisi
FROM 
    (SELECT 0 as seq UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION 
     SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION 
     SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION 
     SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION 
     SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION 
     SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29) days
CROSS JOIN 
    (SELECT 8 as hour_val UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION 
     SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION 
     SELECT 17 UNION SELECT 18) hours
WHERE 
    DATE_ADD(CURDATE(), INTERVAL seq DAY) >= CURDATE();
